import os
from datetime import datetime
from app.agents.base_agent import BaseAgent
from app.core.config import settings

class ReportGeneratorAgent(BaseAgent):
    async def generate(self, report_type: str, source_id: str, user_id: str, data: dict = None) -> dict:
        title = f"{report_type.replace('_', ' ').title()} Report - {datetime.now().strftime('%B %d, %Y')}"
        summary = f"AI-generated {report_type} analysis with detailed insights and recommendations."
        file_path = await self._generate_pdf(report_type, title, user_id, data or {})
        return {"title": title, "summary": summary, "file_path": file_path}

    async def _generate_pdf(self, report_type: str, title: str, user_id: str, data: dict) -> str:
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.lib import colors
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
            from reportlab.lib.units import inch

            os.makedirs(settings.UPLOAD_DIR, exist_ok=True)
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            file_path = os.path.join(settings.UPLOAD_DIR, f"report_{user_id}_{report_type}_{ts}.pdf")

            doc = SimpleDocTemplate(file_path, pagesize=letter,
                                   topMargin=0.75*inch, bottomMargin=0.75*inch,
                                   leftMargin=0.75*inch, rightMargin=0.75*inch)
            styles = getSampleStyleSheet()
            story = []

            # Custom styles
            title_style = ParagraphStyle("CustomTitle", parent=styles["Title"],
                                        textColor=colors.HexColor("#6366f1"), fontSize=22, spaceAfter=6)
            h2_style = ParagraphStyle("H2", parent=styles["Heading2"],
                                     textColor=colors.HexColor("#4338ca"), fontSize=14, spaceAfter=4)
            body_style = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10, spaceAfter=4, leading=14)
            bullet_style = ParagraphStyle("Bullet", parent=styles["Normal"], fontSize=10,
                                         leftIndent=20, spaceAfter=3, leading=13)

            # Header
            story.append(Paragraph("🚀 InterviewAce AI", title_style))
            story.append(Paragraph(title, styles["Heading1"]))
            story.append(Paragraph(f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", styles["Normal"]))
            story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#6366f1")))
            story.append(Spacer(1, 0.2*inch))

            if report_type == "interview":
                self._build_interview_report(story, data, styles, h2_style, body_style, bullet_style)
            elif report_type == "resume":
                self._build_resume_report(story, data, styles, h2_style, body_style, bullet_style)
            elif report_type == "career":
                self._build_career_report(story, data, styles, h2_style, body_style, bullet_style)

            # Footer
            story.append(Spacer(1, 0.3*inch))
            story.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
            story.append(Paragraph("Generated by InterviewAce AI • Prepare. Practice. Perform. Get Hired.", 
                                   ParagraphStyle("footer", parent=styles["Normal"], fontSize=8, 
                                                 textColor=colors.grey, alignment=1)))
            doc.build(story)
            return file_path
        except Exception as e:
            print(f"PDF generation error: {e}")
            return ""

    def _build_interview_report(self, story, data, styles, h2, body, bullet):
        from reportlab.platypus import Paragraph, Spacer, Table, TableStyle
        from reportlab.lib import colors

        scores = data.get("scores", {})
        story.append(Paragraph("📊 Interview Performance Report", h2))
        
        if scores:
            overall = scores.get("overall", 0)
            story.append(Paragraph(f"Overall Score: {overall}/100", body))
            
            score_data = [["Category", "Score", "Grade"]]
            for key, val in scores.items():
                if key != "overall":
                    grade = "A" if val >= 85 else "B" if val >= 70 else "C" if val >= 55 else "D"
                    score_data.append([key.replace("_", " ").title(), f"{val}/100", grade])
            
            t = Table(score_data, colWidths=[2.5*72, 1.5*72, 72])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#6366f1")),
                ("TEXTCOLOR", (0,0), (-1,0), colors.white),
                ("FONTSIZE", (0,0), (-1,-1), 9),
                ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
                ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, colors.HexColor("#f8f9ff")]),
            ]))
            story.append(t)
            story.append(Spacer(1, 0.15*72))

        for section, items in [("✅ Strengths", data.get("strong_areas", [])),
                               ("❌ Areas to Improve", data.get("weak_areas", [])),
                               ("💡 Top Recommendations", data.get("top_improvements", []))]:
            if items:
                story.append(Paragraph(section, h2))
                for item in items:
                    story.append(Paragraph(f"• {item}", bullet))
                story.append(Spacer(1, 0.1*72))

    def _build_resume_report(self, story, data, styles, h2, body, bullet):
        from reportlab.platypus import Paragraph, Spacer
        story.append(Paragraph("📄 Resume Analysis Report", h2))
        story.append(Paragraph(f"Overall Resume Score: {data.get('overall', 'N/A')}/100", body))
        story.append(Paragraph(f"ATS Score: {data.get('ats_score', 'N/A')}/100", body))
        story.append(Spacer(1, 0.1*72))
        
        for section, items in [("Key Strengths", data.get("strengths", [])),
                               ("Areas for Improvement", data.get("improvements", [])),
                               ("Missing Keywords", data.get("keyword_gaps", []))]:
            if items:
                story.append(Paragraph(section, h2))
                for item in items:
                    story.append(Paragraph(f"• {item}", bullet))

    def _build_career_report(self, story, data, styles, h2, body, bullet):
        from reportlab.platypus import Paragraph, Spacer
        story.append(Paragraph("🗺️ Career Roadmap Report", h2))
        story.append(Paragraph(f"Path: {data.get('current_role', 'Current')} → {data.get('target_role', 'Target')}", body))
        story.append(Paragraph(f"Timeline: {data.get('timeline_months', 12)} months", body))
        story.append(Spacer(1, 0.1*72))
        
        for milestone in data.get("milestones", []):
            story.append(Paragraph(f"🎯 {milestone.get('title', '')}", h2))
            story.append(Paragraph(milestone.get("description", ""), body))
            story.append(Paragraph(f"Timeline: {milestone.get('timeline', '')}", body))
